finalmovieproject/credentials/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView,PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views
from . views import MyLoginView,RegisterView,MyProfile
app_name='credentials'

urlpatterns = [
    # path('test/', views.home,name='home'),
    path('login/', MyLoginView.as_view(),name='login'),
    path('logout/', LogoutView.as_view(next_page='finalmovieapp:allMoviesCat'),name='logout'),
    path('register/', RegisterView.as_view(),name='register'),
    path('profile/', MyProfile.as_view(), name='profile'),

    ]

finalmovieproject/finalmovieapp/urls.py
from . import views
from django.urls import path
app_name='finalmovieapp'
from .views import MovieCreateView,MovieListView,CommentCreateView

urlpatterns = [
    # path('',views.home,name='home'),
    path('',views.allMoviesCat,name='allMoviesCat'),

    path('cbvadd/', MovieCreateView.as_view(), name='task-create'),
    path('cbvcomment/<int:pk>/', CommentCreateView.as_view(), name='add_comment'),
    path('movies/', MovieListView.as_view(),name='movies'),
    path('cbvupdate/<int:pk>/', views.MovieUpdateView.as_view(), name='cbvupdate'),
    path('cbvdelete/<int:pk>/', views.MovieDeleteView.as_view(), name='cbvdelete'),

    path('<slug:c_slug>/' ,views.allMoviesCat,name='movie_by_category'),
    path('<slug:c_slug>/<slug:movie_slug>/', views.movieDetail, name='moviesCatDetail'),




    ]

finalmovieproject/finalmovieproject/urls.py
from finalmovieproject import settings
from  django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('credentials.urls')),
    path('', include('finalmovieapp.urls')),
    path('search', include('searchapp.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finalmovieproject/searchapp/urls.py
from . import views
from django.urls import path
app_name='searchapp'

urlpatterns = [
    path('',views.searchResult,name='searchResult'),

    ]

finalmovieproject/finalmovieapp/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)

    class Meta:
        ordering= ('name', )
        verbose_name='category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('finalmovieapp:movie_by_category', args=[self.slug])
    #go to /category page

    def __str__(self):
        return '{}'.format(self.name)

class Movie(models.Model):
    YEAR_CHOICES = [(y, y) for y in range(1968, datetime.date.today().year + 1)]
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique=True)
    desc = models.TextField()
    date = models.IntegerField(choices=YEAR_CHOICES)
    image = models.ImageField(upload_to='movies',blank=True)
    actors = models.CharField(max_length=250)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    youtubelink = models.URLField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'movie'
        verbose_name_plural = 'movies'

    def get_url(self):
        return reverse('finalmovieapp:moviesCatDetail', args=[self.category.slug,self.slug])
    # go to /category/product page

    def __str__(self):
        return '{}'.format(self.name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Movie, self).save(*args, **kwargs)

class Comment(models.Model):
    movie = models.ForeignKey(Movie,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' %(self.movie.name, self.name)

finalmovieproject/templates/add.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
        Welcome to ABC Store
{% endblock %}

{% block title %}
    {% if category %}
        {{category.name}} - Movie Store
    {% else %}
        Home
    {% endif %}
{% endblock %}

{% block content %}
<br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter movie title"><br><br>
    <input type="text" name="desc" placeholder="Enter movie description"><br><br>
    <input type="date" name="date" placeholder="Enter movie release date"><br><br>
    <input type="text" name="actors" placeholder="Enter movie actors"><br><br>
    <input type="text" name="category" placeholder="Enter movie category"><br><br>
    <input type="text" name="youtubelink" placeholder="Enter movie youtube trailer link"><br><br>
    <input type="file" name="image"><br><br>
    <input type="submit"><br>
</form>

{% endblock %}

finalmovieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="description" content="{% block metadescription %} {% endblock %}" >
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <link href=" {% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src=" {% static 'js/popper.min.js' %}"></script>
    <script src=" {% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://kit.fontawesome.com/9de9ee17fa.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <title>{% block title %} {% endblock %} </title>


</head>
<body>


    {% include 'header.html' %}

    {% if messages %}
				{% for message in messages %}
					<div class="alert alert-{{message.tags}}">
					       {{message}}
					     </div>
					   {% endfor %}
				{% endif %}
    {% block content %}
    {% endblock %}

<br>
{% include 'footer.html' %}

</body>
</html>

finalmovieproject/templates/category.html
<!--home page-->

{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
        Welcome to ABC Store
{% endblock %}

{% block title %}
    {% if category %}
        {{category.name}} - Movie Store
    {% else %}
        Home
    {% endif %}
{% endblock %}

{% block content %}



<div class="mx-auto">
    {% if category %}
</div>
    <br>
    <div>
        <h1 class="text-center my_title">{{category.name}}</h1>
    </div>
    {% else %}
<br>
    <div>
        <h1 class="text-center my-title">Our Movies Store </h1>


    </div>
<br>
    {% endif %}


    <div class="container">
        <div class="row mx-auto">
            {% for movie in movies %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4 ">
                <div class="card text-center" style="min-width: 18rem;">
                    <a href="{{movie.get_url}}"> <img class="card-img-top my_image" style="height:280px;" src="{{movie.image.url}}" alt="{{movie.name}}"> </a>
                    <div class="card-body">
                        <h4><strong>Movie : </strong>{{movie.name}}</h4>
                        <p><strong>Release Date : </strong>{{movie.date}}</p>
                        <p><strong>Actors : </strong>{{movie.actors}}</p>
                        <p><strong>Genre : </strong>{{movie.category}}</p>
                        <a href="{{movie.get_url}}" class="btn btn-warning" >View More Detais</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
<br>

{% endblock %}

finalmovieproject/templates/create.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {{movie.desc|truncatewords:155}}
{% endblock %}

{% block title %}
        {{movie.name}}
{% endblock %}

{% block content %}

<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task Update
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
            <button type="submit">Confirm</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

finalmovieproject/templates/delete.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
        Welcome to ABC Store
{% endblock %}

{% block title %}
    {% if category %}
        {{category.name}} - Movie Store
    {% else %}
        Home
    {% endif %}
{% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <p> Are you sure you want to delete this movie ? </p>
    <button type="submit"> Confirm </button>
</form>




{% endblock %}

finalmovieproject/templates/header.html
{% load static %}


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    <img src="{% static 'img/logo.jpg' %}" width="40" height="30" class="d-inline-block align-top" alt="">
    Movie Store
  </a>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'finalmovieapp:allMoviesCat' %}">All Movies</a>
            <div class="dropdown-divider"></div>
            {% for cat in links %}
            <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
            {% endfor %}

        </div>
      </li>
    </ul>



      {% if user.is_authenticated %}

        <a href="{% url 'credentials:profile' %}" title="Update my profile">Hi {{request.user | title}}, View Profile </a>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 profile-menu">
            <li class="nav-item dropdown">

                <a class="nav-link dropdown-toggle" id="navbarDropdown1" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="profile-pic">
                        <img src="{{user.profile.avatar.url}}" alt="Profile Picture" width="40px" height="40px">
                    </div>
                    <!-- You can also use icon as follows: -->
                    <!--  <i class="fas fa-user"></i> -->
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown1">
                    <li><a class="dropdown-item" href="{% url 'credentials:profile' %}"> Edit Profile </a></li>
                    <li><a class="dropdown-item" href="/cbvadd"> Add Movies </a></li>
                    <li><a class="dropdown-item" href="{% url 'finalmovieapp:movies' %}"> View Added Movies </a></li>

                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="/logout"><i class="fas fa-sign-out-alt fa-fw"></i> Log Out</a></li>
                </ul>
            </li>
        </ul>

       {% else %}
        <button style="margin-left:10px; margin-right:10px;" class="btn btn-danger" onclick='window.location.href = "/register"'>Register</button>

        <button style="margin-left:10px; margin-right:10px;" class="btn btn-danger navbar-btn" onclick='window.location.href = "/login"'>Login</button>
       {% endif %}


        <form class="form-inline my-2 my-lg-0" action="{% url 'searchapp:searchResult' %}" method="get" >
            {% csrf_token %}
            <input style="text-align:right;" class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
            <button style="text-align:right;" class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>


    </div>
</nav>

<!--https://source.unsplash.com/250x250?girl-->

finalmovieproject/templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="css/home.css">

    <title>Home</title>
  </head>
  <body>
    <header>
        <nav class="navbar">
            <p class="logo">Profile</p>
                <a class="profile-icon-link-container" href="profile.html">
                    <img src="images/default.svg" alt="profile-icon">
                    <span class="header-username">Hello, Nitin</span>
                </a>
        </nav>
    </header>

    <script>
        var cross = document.getElementById('cross')
        cross.addEventListener('click', ()=> {
            document.getElementsByClassName('notification-container')[0].style.display = 'none';
        })

    </script>


    <main class="main-container">
        <div class="container">
            <div class="profile-photo-container">
                <img src="images/default.jpg" alt="User Image" width="100px" srcset="">
            </div>


            <div class="user-content-container">
                <p class="username">John Doe (Default)</p>
                <p class="user-title">A web developer/ full stack developer.</p>
                <p class="user-desc">This is the default, title change it in profile.</p>
                <div class="profile-edit-link-container">
                    <a href="profile.html">Edit</a>
                </div>
            </div>
        </div>
    </main>
  </body>
</html>

finalmovieproject/templates/index.html
{% extends 'base.html' %}

{% block body %}


<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
             <div class="card"  style="width: 15rem; margin-top:20px;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="250">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text">{{i.year}}</p>
                    <a href="{% url 'finalmovieapp:detail' i.id %}" class="btn btn-primary">View Details</a>
                </div>
            </div><br>
        </div>
        {% endfor %}
    </div>
</div>




{% endblock %}

finalmovieproject/templates/movie.html
<!--details of each movie page-->

{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {{movie.desc|truncatewords:155}}
{% endblock %}

{% block title %}
        {{movie.name}}
{% endblock %}

{% block content %}



<div class="row my_prod_row_class">
    <div class="mx-auto">
        <br>
        <p><a href="{% url 'finalmovieapp:allMoviesCat' %}">Home</a> |
            <a href="{{movie.category.get_url}}">{{movie.category}} </a> | {{movie.name}} </p>
    </div>
</div>

<div class="container">
    <br>

    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width: 18rem;">
                <img src="{{movie.image.url}}" alt="{{movie.name}}" height="450px" width="500px">
            </div>
        </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1 class="my_prod_title"><strong>Movie : </strong>{{movie.name}}</h1>
                <p><strong>Release Date : </strong>{{movie.date}}</p>
                <p><strong>Actors : </strong>{{movie.actors}}</p>
                <p><strong>Genre : </strong>{{movie.category}}</p>


                <p class="my_prod_title"><strong>Product Description : </strong></p>
                <p class="text-justify my_prod_text">{{movie.desc}}</p>

                <p><strong>Trailer : </strong><a href="{{movie.youtubelink}}">{{movie.youtubelink}}</a></p>
                <p><strong>Uploaded by : </strong>{{movie.user}}</p>
                <a class="btn btn-warning" href="{% url 'finalmovieapp:cbvupdate' movie.id %}">Update </a>
                <a class="btn btn-danger" href="{% url 'finalmovieapp:cbvdelete' movie.id %}">Delete </a>

                <br>
                <br>
                <hr>
                <h2>Comments..</h2>

                {% if not movie.comments.all %}
                    No comments yet..<a href="{% url 'finalmovieapp:add_comment' movie.pk %}">Add One</a>
                {% else %}
                <a href="{% url 'finalmovieapp:add_comment' movie.pk %}"> Add Comments </a>
                <br>
                <br>
                    {% for comment in movie.comments.all %}
                        <strong>
                            {{comment.name}} -
                            {{comment.date_added}}
                        </strong>
                        <br>
                        {{comment.body}}
                <br>
                <br>

                {% endfor %}
                {% endif %}
                <br>
                <hr>







            </div>
        </div>
        <br>
    </div>
</div>
<br><br><br>

{% endblock %}

finalmovieproject/templates/profile.html
{% extends 'base.html' %} 

{% block content %}

<br>
<br>
<div class="center">
	<br>
	<br>
<br>
	<br>
<br>
	<br><br>
<br>
<br>
	<form method="POST" enctype="multipart/form-data" class="card">
		{% csrf_token %} 
		
	    {% if user.profile %}
			<img src="{{user.profile.avatar.url}}" alt="{{ user.username }}" class="avatar" accept=".jpg,.jpeg,.png"/>
	    {% endif %}
	    
	    <h2 class="text-center">{{ user.username | title }}</h2>
	    <p class="text-center"><a href="mailto:{{user.email}}">{{user.email}}</a></p>
   	    <hr>
		
            <label for="email">Email Address:</label>
            <input type="email" id="email" name="email" value="{{user.email}}" />


            <label for="first_name">First Name:</label>
            <input type="text" id="first_name" name="first_name" value="{{user.first_name}}" />

			<label for="last_name">First Name:</label>
            <input type="text" id="last_name" name="last_name" value="{{user.last_name}}" />
			
		
		<label for="avatar">Avatar:</label>
		<input type="file" name="avatar" id="avatar">	
		
	    <button type="submit" class="btn btn-primary full-width">Update Profile</button>
	<br>
<br>
	</form>


</div>


<br>

{% endblock content %}

finalmovieproject/templates/register.html
{%extends 'base.html'%}

{%block content%}
	<div class="center">
	  <form method="post" novaldiate class="card">
	  	{% csrf_token %}
	    <h2 class="text-center">Create your account</h2>
		{% for field in form %}
	    		{{ field.label_tag }} 
	        	{{ field }}
	        	{% if field.errors %}
	        		<small class="error">{{ field.errors|striptags  }}</small> 
	        	{% endif %}
		{% endfor %}
		
		<input type="submit" value="Register" class="btn btn-primary full-width">
		<hr>
		<p class="text-center">Already have an account? <a href="{% url 'credentials:login' %}">Login Here</a></p>
		</form>
	</div>
{%endblock content%}

finalmovieproject/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
        Welcome to ABC Store
{% endblock %}

{% block title %}
    {% if category %}
        {{category.name}} - Movie Store
    {% else %}
        Home
    {% endif %}
{% endblock %}

{% block content %}

<div>
    <p class="text-center my_search_text">
        You have searched for : <b>"{{query}}"</b>
    </p>
</div>

<div class="container">
        <div class="row mx-auto">
            {% for movie in movies %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4 ">
                <div class="card text-center" style="min-width: 18rem;">
                    <a href="{{movie.get_url}}"> <img class="card-img-top my_image" style="height:280px;" src="{{movie.image.url}}" alt="{{movie.name}}"> </a>
                    <div class="card-body">
                        <h4>{{movie.name}}</h4>
                        <p>{{movie.date}}</p>
                        <p>{{movie.category}}</p>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="row mx-auto">
                <p class="text-center my_search_text">0 results found</p>
            </div>
            {% endfor %}


        </div>
</div>

{% endblock %}

finalmovieproject/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
tteeeeeessssssttttttt
</body>
</html>

finalmovieproject/templates/update.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {{movie.desc|truncatewords:155}}
{% endblock %}

{% block title %}
        {{movie.name}}
{% endblock %}

{% block content %}
<div class="container">
<div class="card">
    <div class="card-header">
        <div class="card-title">
            <h3>  Movie Update </h3>
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
            <button type="submit">Confirm</button>
            </form>
        </div>
    </div>
</div>
</div>



{% endblock %}